language: emacs-lisp
sudo: false
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask install
script:
  - cask exec buttercup -L . -L tests

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-25.1-travis
    - env: EVM_EMACS=emacs-git-snapshot-travis
